### ISSUE TITLE
мяч можно протолкнуть сквозь коллайдер

### ISSUE THREAD

**Issue by Delivery-Klad** [RTUITLab/Screen-ArkoPong-Unity#1]
пофиксите пожалуйста))))

**Comment by CAPCHIK** [comment]
@Delivery-Klad  Можешь описать, как именно воспроизводится ошибка?

**Comment by Delivery-Klad** [comment]
Необходимо вовремя двинуть платформой вверх и прижать мяч к верхней границе, после чего останется только 1 мяч
